language: python
python:
- 3.6
- 3.5
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: pip install -U tox-travis
script: tox
deploy:
  on:
    all_branches: true
    tags: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: Joseph.Rawson
  password:
    secure: Hrw8g8G9ltqG+z7ShuWrKF2aDU6llSKCL8rRpy6YYszT1ymIMq7g1q23V7c5Mr1T/jx4JbuvrBr9bMg8u8fuSvoivtgG+m9JW/6CQYjPWofKFufv1nGwitBz6NZhmnkFEkxfa6uehCh+g1Oy1KZHEUwdkP1MGSzRTSXy9vNG65Q=
